services:
  #Container 1: PostgreSQL and pgvector extension
  db:
    image: pgvector/pgvector:pg17           #image is already in pgvector
    environment: 
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"                         #host container
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  #Container 2: Streamlit app
  app:
    build:
      context:
      dockerfile: docker/Dockerfile
    ports: "8501:8501"
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB}
    depends_on:
      db:
        condition: service_healthy
      volumes:
        - ./app:/multimodal-doc-assistant/app
volumes:
  pgdata: